apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-login
  labels:
    app: vue-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-login
  template:
    metadata:
      labels:
        app: vue-login
    spec:
      containers:
      - name: vue-login
        image: ${DOCKER_REGISTRY}/vue-login:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5