stages:
  - deploy

deploy-job:
  image: node:16
  cache:
    paths:
      - node_modules/
  only:
    - main
  stage: deploy
  script:
    - npm i -g @cloudtype/cli
    - ctype login -t $API_KEY_TOKEN
    # 디렉토리 생성
    - mkdir -p ./.cloudtype
    # vue-login.yaml 파일 생성
    - |
      cat <<EOF > ./vue-login.yaml
      name: vue-login
      app: web
      options:
        nodeversion: "16"
        build: npm run build
        spa: true
        buildenv: []
        rewrites: []
      context:
        git:
          url: git@gitlab.com:$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME.git
          branch: main
        preset: vue
      EOF
    - cat ./vue-login.yaml
    # 클라우드타입에 바로 배포
    - cat ./.cloudtype/app.yaml
    - ctype apply -f ./vue-login.yaml