stages:
  - build_and_deploy

deploy-job:
  image: node:16
  stage: build_and_deploy
  script:
    # 타임스탬프 파일 생성
    - echo "Build timestamp: $(date)" > src/timestamp.js
    # 의존성 설치 및 빌드
    - npm install
    - npm run build
    
    # Cloudtype CLI 설치 및 로그인
    - npm i -g @cloudtype/cli
    - ctype login -t $API_KEY_TOKEN
    
    # 디렉토리 생성
    - mkdir -p ./.cloudtype
    
    # 배포 설정 파일 생성
    - |
      cat <<EOF > ./deploy.yaml
      name: vue-login
      app: web
      options:
        nodeversion: "16"
        spa: true
      context:
        web:
          path: ./dist
      EOF
    
    # 배포 실행
    - ctype apply -f ./deploy.yaml